//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36392
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.36392.
// 
#pragma warning disable 1591

namespace gdpv2.AlfaWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlfaWSSoap", Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public partial class AlfaWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EntidadesSingularesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EntidadesSingularesMuniOperationCompleted;
        
        private System.Threading.SendOrPostCallback MunicipiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalCodPortalOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalesEntidadNombreCasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalesNombreEntidadSingularOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalesNombreLocalidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostalesViaNombreCasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViasEntidadSingularOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViasLocalidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViasMunicipiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViasNombreViaEntSingularOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViasNombreViaLocalidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlfaWS() {
            this.Url = global::gdpv2.Properties.Settings.Default.gdpv2_AlfaWS_AlfaWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EntidadesSingularesCompletedEventHandler EntidadesSingularesCompleted;
        
        /// <remarks/>
        public event EntidadesSingularesMuniCompletedEventHandler EntidadesSingularesMuniCompleted;
        
        /// <remarks/>
        public event MunicipiosCompletedEventHandler MunicipiosCompleted;
        
        /// <remarks/>
        public event PostalCompletedEventHandler PostalCompleted;
        
        /// <remarks/>
        public event PostalCodPortalCompletedEventHandler PostalCodPortalCompleted;
        
        /// <remarks/>
        public event PostalesCompletedEventHandler PostalesCompleted;
        
        /// <remarks/>
        public event PostalesEntidadNombreCasaCompletedEventHandler PostalesEntidadNombreCasaCompleted;
        
        /// <remarks/>
        public event PostalesNombreEntidadSingularCompletedEventHandler PostalesNombreEntidadSingularCompleted;
        
        /// <remarks/>
        public event PostalesNombreLocalidadCompletedEventHandler PostalesNombreLocalidadCompleted;
        
        /// <remarks/>
        public event PostalesViaNombreCasaCompletedEventHandler PostalesViaNombreCasaCompleted;
        
        /// <remarks/>
        public event ViaCompletedEventHandler ViaCompleted;
        
        /// <remarks/>
        public event ViasEntidadSingularCompletedEventHandler ViasEntidadSingularCompleted;
        
        /// <remarks/>
        public event ViasLocalidadCompletedEventHandler ViasLocalidadCompleted;
        
        /// <remarks/>
        public event ViasMunicipiosCompletedEventHandler ViasMunicipiosCompleted;
        
        /// <remarks/>
        public event ViasNombreViaEntSingularCompletedEventHandler ViasNombreViaEntSingularCompleted;
        
        /// <remarks/>
        public event ViasNombreViaLocalidadCompletedEventHandler ViasNombreViaLocalidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/EntidadesSingulares", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass EntidadesSingulares(string pPatron, Idioma pIdioma) {
            object[] results = this.Invoke("EntidadesSingulares", new object[] {
                        pPatron,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void EntidadesSingularesAsync(string pPatron, Idioma pIdioma) {
            this.EntidadesSingularesAsync(pPatron, pIdioma, null);
        }
        
        /// <remarks/>
        public void EntidadesSingularesAsync(string pPatron, Idioma pIdioma, object userState) {
            if ((this.EntidadesSingularesOperationCompleted == null)) {
                this.EntidadesSingularesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntidadesSingularesOperationCompleted);
            }
            this.InvokeAsync("EntidadesSingulares", new object[] {
                        pPatron,
                        pIdioma}, this.EntidadesSingularesOperationCompleted, userState);
        }
        
        private void OnEntidadesSingularesOperationCompleted(object arg) {
            if ((this.EntidadesSingularesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EntidadesSingularesCompleted(this, new EntidadesSingularesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/EntidadesSingularesMuni", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass EntidadesSingularesMuni(short pCodMun, string pPatron, Idioma pIdioma) {
            object[] results = this.Invoke("EntidadesSingularesMuni", new object[] {
                        pCodMun,
                        pPatron,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void EntidadesSingularesMuniAsync(short pCodMun, string pPatron, Idioma pIdioma) {
            this.EntidadesSingularesMuniAsync(pCodMun, pPatron, pIdioma, null);
        }
        
        /// <remarks/>
        public void EntidadesSingularesMuniAsync(short pCodMun, string pPatron, Idioma pIdioma, object userState) {
            if ((this.EntidadesSingularesMuniOperationCompleted == null)) {
                this.EntidadesSingularesMuniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntidadesSingularesMuniOperationCompleted);
            }
            this.InvokeAsync("EntidadesSingularesMuni", new object[] {
                        pCodMun,
                        pPatron,
                        pIdioma}, this.EntidadesSingularesMuniOperationCompleted, userState);
        }
        
        private void OnEntidadesSingularesMuniOperationCompleted(object arg) {
            if ((this.EntidadesSingularesMuniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EntidadesSingularesMuniCompleted(this, new EntidadesSingularesMuniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/Municipios", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass Municipios(string pPatron, Idioma pIdioma) {
            object[] results = this.Invoke("Municipios", new object[] {
                        pPatron,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void MunicipiosAsync(string pPatron, Idioma pIdioma) {
            this.MunicipiosAsync(pPatron, pIdioma, null);
        }
        
        /// <remarks/>
        public void MunicipiosAsync(string pPatron, Idioma pIdioma, object userState) {
            if ((this.MunicipiosOperationCompleted == null)) {
                this.MunicipiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMunicipiosOperationCompleted);
            }
            this.InvokeAsync("Municipios", new object[] {
                        pPatron,
                        pIdioma}, this.MunicipiosOperationCompleted, userState);
        }
        
        private void OnMunicipiosOperationCompleted(object arg) {
            if ((this.MunicipiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MunicipiosCompleted(this, new MunicipiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/Postal", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass Postal(int pCodVia, string pNumero, Idioma pIdioma) {
            object[] results = this.Invoke("Postal", new object[] {
                        pCodVia,
                        pNumero,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalAsync(int pCodVia, string pNumero, Idioma pIdioma) {
            this.PostalAsync(pCodVia, pNumero, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalAsync(int pCodVia, string pNumero, Idioma pIdioma, object userState) {
            if ((this.PostalOperationCompleted == null)) {
                this.PostalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalOperationCompleted);
            }
            this.InvokeAsync("Postal", new object[] {
                        pCodVia,
                        pNumero,
                        pIdioma}, this.PostalOperationCompleted, userState);
        }
        
        private void OnPostalOperationCompleted(object arg) {
            if ((this.PostalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalCompleted(this, new PostalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/PostalCodPortal", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass PostalCodPortal(int pCodPortal, Idioma pIdioma) {
            object[] results = this.Invoke("PostalCodPortal", new object[] {
                        pCodPortal,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalCodPortalAsync(int pCodPortal, Idioma pIdioma) {
            this.PostalCodPortalAsync(pCodPortal, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalCodPortalAsync(int pCodPortal, Idioma pIdioma, object userState) {
            if ((this.PostalCodPortalOperationCompleted == null)) {
                this.PostalCodPortalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalCodPortalOperationCompleted);
            }
            this.InvokeAsync("PostalCodPortal", new object[] {
                        pCodPortal,
                        pIdioma}, this.PostalCodPortalOperationCompleted, userState);
        }
        
        private void OnPostalCodPortalOperationCompleted(object arg) {
            if ((this.PostalCodPortalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalCodPortalCompleted(this, new PostalCodPortalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/Postales", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass Postales(int pCodVia, string pNumero, Idioma pIdioma) {
            object[] results = this.Invoke("Postales", new object[] {
                        pCodVia,
                        pNumero,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalesAsync(int pCodVia, string pNumero, Idioma pIdioma) {
            this.PostalesAsync(pCodVia, pNumero, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalesAsync(int pCodVia, string pNumero, Idioma pIdioma, object userState) {
            if ((this.PostalesOperationCompleted == null)) {
                this.PostalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalesOperationCompleted);
            }
            this.InvokeAsync("Postales", new object[] {
                        pCodVia,
                        pNumero,
                        pIdioma}, this.PostalesOperationCompleted, userState);
        }
        
        private void OnPostalesOperationCompleted(object arg) {
            if ((this.PostalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalesCompleted(this, new PostalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/PostalesEntidadNombreCasa", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass PostalesEntidadNombreCasa(int pCodEntSing, string pNomCasa, Idioma pIdioma) {
            object[] results = this.Invoke("PostalesEntidadNombreCasa", new object[] {
                        pCodEntSing,
                        pNomCasa,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalesEntidadNombreCasaAsync(int pCodEntSing, string pNomCasa, Idioma pIdioma) {
            this.PostalesEntidadNombreCasaAsync(pCodEntSing, pNomCasa, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalesEntidadNombreCasaAsync(int pCodEntSing, string pNomCasa, Idioma pIdioma, object userState) {
            if ((this.PostalesEntidadNombreCasaOperationCompleted == null)) {
                this.PostalesEntidadNombreCasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalesEntidadNombreCasaOperationCompleted);
            }
            this.InvokeAsync("PostalesEntidadNombreCasa", new object[] {
                        pCodEntSing,
                        pNomCasa,
                        pIdioma}, this.PostalesEntidadNombreCasaOperationCompleted, userState);
        }
        
        private void OnPostalesEntidadNombreCasaOperationCompleted(object arg) {
            if ((this.PostalesEntidadNombreCasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalesEntidadNombreCasaCompleted(this, new PostalesEntidadNombreCasaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/PostalesNombreEntidadSingular", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass PostalesNombreEntidadSingular(int pCodEntSing, string pVia, string pNumero, Idioma pIdioma) {
            object[] results = this.Invoke("PostalesNombreEntidadSingular", new object[] {
                        pCodEntSing,
                        pVia,
                        pNumero,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalesNombreEntidadSingularAsync(int pCodEntSing, string pVia, string pNumero, Idioma pIdioma) {
            this.PostalesNombreEntidadSingularAsync(pCodEntSing, pVia, pNumero, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalesNombreEntidadSingularAsync(int pCodEntSing, string pVia, string pNumero, Idioma pIdioma, object userState) {
            if ((this.PostalesNombreEntidadSingularOperationCompleted == null)) {
                this.PostalesNombreEntidadSingularOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalesNombreEntidadSingularOperationCompleted);
            }
            this.InvokeAsync("PostalesNombreEntidadSingular", new object[] {
                        pCodEntSing,
                        pVia,
                        pNumero,
                        pIdioma}, this.PostalesNombreEntidadSingularOperationCompleted, userState);
        }
        
        private void OnPostalesNombreEntidadSingularOperationCompleted(object arg) {
            if ((this.PostalesNombreEntidadSingularCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalesNombreEntidadSingularCompleted(this, new PostalesNombreEntidadSingularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/PostalesNombreLocalidad", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass PostalesNombreLocalidad(string pLocalidad, string pVia, string pNumero, Idioma pIdioma) {
            object[] results = this.Invoke("PostalesNombreLocalidad", new object[] {
                        pLocalidad,
                        pVia,
                        pNumero,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalesNombreLocalidadAsync(string pLocalidad, string pVia, string pNumero, Idioma pIdioma) {
            this.PostalesNombreLocalidadAsync(pLocalidad, pVia, pNumero, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalesNombreLocalidadAsync(string pLocalidad, string pVia, string pNumero, Idioma pIdioma, object userState) {
            if ((this.PostalesNombreLocalidadOperationCompleted == null)) {
                this.PostalesNombreLocalidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalesNombreLocalidadOperationCompleted);
            }
            this.InvokeAsync("PostalesNombreLocalidad", new object[] {
                        pLocalidad,
                        pVia,
                        pNumero,
                        pIdioma}, this.PostalesNombreLocalidadOperationCompleted, userState);
        }
        
        private void OnPostalesNombreLocalidadOperationCompleted(object arg) {
            if ((this.PostalesNombreLocalidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalesNombreLocalidadCompleted(this, new PostalesNombreLocalidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/PostalesViaNombreCasa", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass PostalesViaNombreCasa(int pCodVia, string pNomCasa, Idioma pIdioma) {
            object[] results = this.Invoke("PostalesViaNombreCasa", new object[] {
                        pCodVia,
                        pNomCasa,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void PostalesViaNombreCasaAsync(int pCodVia, string pNomCasa, Idioma pIdioma) {
            this.PostalesViaNombreCasaAsync(pCodVia, pNomCasa, pIdioma, null);
        }
        
        /// <remarks/>
        public void PostalesViaNombreCasaAsync(int pCodVia, string pNomCasa, Idioma pIdioma, object userState) {
            if ((this.PostalesViaNombreCasaOperationCompleted == null)) {
                this.PostalesViaNombreCasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostalesViaNombreCasaOperationCompleted);
            }
            this.InvokeAsync("PostalesViaNombreCasa", new object[] {
                        pCodVia,
                        pNomCasa,
                        pIdioma}, this.PostalesViaNombreCasaOperationCompleted, userState);
        }
        
        private void OnPostalesViaNombreCasaOperationCompleted(object arg) {
            if ((this.PostalesViaNombreCasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostalesViaNombreCasaCompleted(this, new PostalesViaNombreCasaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/Via", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass Via(int pCodVia, Idioma pIdioma) {
            object[] results = this.Invoke("Via", new object[] {
                        pCodVia,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void ViaAsync(int pCodVia, Idioma pIdioma) {
            this.ViaAsync(pCodVia, pIdioma, null);
        }
        
        /// <remarks/>
        public void ViaAsync(int pCodVia, Idioma pIdioma, object userState) {
            if ((this.ViaOperationCompleted == null)) {
                this.ViaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViaOperationCompleted);
            }
            this.InvokeAsync("Via", new object[] {
                        pCodVia,
                        pIdioma}, this.ViaOperationCompleted, userState);
        }
        
        private void OnViaOperationCompleted(object arg) {
            if ((this.ViaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViaCompleted(this, new ViaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/ViasEntidadSingular", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass ViasEntidadSingular(int pCodEntSing, string pPatron, Idioma pIdioma) {
            object[] results = this.Invoke("ViasEntidadSingular", new object[] {
                        pCodEntSing,
                        pPatron,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void ViasEntidadSingularAsync(int pCodEntSing, string pPatron, Idioma pIdioma) {
            this.ViasEntidadSingularAsync(pCodEntSing, pPatron, pIdioma, null);
        }
        
        /// <remarks/>
        public void ViasEntidadSingularAsync(int pCodEntSing, string pPatron, Idioma pIdioma, object userState) {
            if ((this.ViasEntidadSingularOperationCompleted == null)) {
                this.ViasEntidadSingularOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViasEntidadSingularOperationCompleted);
            }
            this.InvokeAsync("ViasEntidadSingular", new object[] {
                        pCodEntSing,
                        pPatron,
                        pIdioma}, this.ViasEntidadSingularOperationCompleted, userState);
        }
        
        private void OnViasEntidadSingularOperationCompleted(object arg) {
            if ((this.ViasEntidadSingularCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViasEntidadSingularCompleted(this, new ViasEntidadSingularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/ViasLocalidad", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass ViasLocalidad(string pLocalidad, string pPatron, Idioma pIdioma) {
            object[] results = this.Invoke("ViasLocalidad", new object[] {
                        pLocalidad,
                        pPatron,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void ViasLocalidadAsync(string pLocalidad, string pPatron, Idioma pIdioma) {
            this.ViasLocalidadAsync(pLocalidad, pPatron, pIdioma, null);
        }
        
        /// <remarks/>
        public void ViasLocalidadAsync(string pLocalidad, string pPatron, Idioma pIdioma, object userState) {
            if ((this.ViasLocalidadOperationCompleted == null)) {
                this.ViasLocalidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViasLocalidadOperationCompleted);
            }
            this.InvokeAsync("ViasLocalidad", new object[] {
                        pLocalidad,
                        pPatron,
                        pIdioma}, this.ViasLocalidadOperationCompleted, userState);
        }
        
        private void OnViasLocalidadOperationCompleted(object arg) {
            if ((this.ViasLocalidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViasLocalidadCompleted(this, new ViasLocalidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/ViasMunicipios", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass ViasMunicipios(short pCodMun, string pPatron, Idioma pIdioma) {
            object[] results = this.Invoke("ViasMunicipios", new object[] {
                        pCodMun,
                        pPatron,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void ViasMunicipiosAsync(short pCodMun, string pPatron, Idioma pIdioma) {
            this.ViasMunicipiosAsync(pCodMun, pPatron, pIdioma, null);
        }
        
        /// <remarks/>
        public void ViasMunicipiosAsync(short pCodMun, string pPatron, Idioma pIdioma, object userState) {
            if ((this.ViasMunicipiosOperationCompleted == null)) {
                this.ViasMunicipiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViasMunicipiosOperationCompleted);
            }
            this.InvokeAsync("ViasMunicipios", new object[] {
                        pCodMun,
                        pPatron,
                        pIdioma}, this.ViasMunicipiosOperationCompleted, userState);
        }
        
        private void OnViasMunicipiosOperationCompleted(object arg) {
            if ((this.ViasMunicipiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViasMunicipiosCompleted(this, new ViasMunicipiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/ViasNombreViaEntSingular", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass ViasNombreViaEntSingular(int pCodEntSing, string pVia, Idioma pIdioma) {
            object[] results = this.Invoke("ViasNombreViaEntSingular", new object[] {
                        pCodEntSing,
                        pVia,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void ViasNombreViaEntSingularAsync(int pCodEntSing, string pVia, Idioma pIdioma) {
            this.ViasNombreViaEntSingularAsync(pCodEntSing, pVia, pIdioma, null);
        }
        
        /// <remarks/>
        public void ViasNombreViaEntSingularAsync(int pCodEntSing, string pVia, Idioma pIdioma, object userState) {
            if ((this.ViasNombreViaEntSingularOperationCompleted == null)) {
                this.ViasNombreViaEntSingularOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViasNombreViaEntSingularOperationCompleted);
            }
            this.InvokeAsync("ViasNombreViaEntSingular", new object[] {
                        pCodEntSing,
                        pVia,
                        pIdioma}, this.ViasNombreViaEntSingularOperationCompleted, userState);
        }
        
        private void OnViasNombreViaEntSingularOperationCompleted(object arg) {
            if ((this.ViasNombreViaEntSingularCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViasNombreViaEntSingularCompleted(this, new ViasNombreViaEntSingularCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tracasa.es/Schemas/GDP/ViasNombreViaLocalidad", RequestNamespace="http://www.tracasa.es/Schemas/GDP/", ResponseNamespace="http://www.tracasa.es/Schemas/GDP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GDPClass ViasNombreViaLocalidad(string pLocalidad, string pVia, Idioma pIdioma) {
            object[] results = this.Invoke("ViasNombreViaLocalidad", new object[] {
                        pLocalidad,
                        pVia,
                        pIdioma});
            return ((GDPClass)(results[0]));
        }
        
        /// <remarks/>
        public void ViasNombreViaLocalidadAsync(string pLocalidad, string pVia, Idioma pIdioma) {
            this.ViasNombreViaLocalidadAsync(pLocalidad, pVia, pIdioma, null);
        }
        
        /// <remarks/>
        public void ViasNombreViaLocalidadAsync(string pLocalidad, string pVia, Idioma pIdioma, object userState) {
            if ((this.ViasNombreViaLocalidadOperationCompleted == null)) {
                this.ViasNombreViaLocalidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViasNombreViaLocalidadOperationCompleted);
            }
            this.InvokeAsync("ViasNombreViaLocalidad", new object[] {
                        pLocalidad,
                        pVia,
                        pIdioma}, this.ViasNombreViaLocalidadOperationCompleted, userState);
        }
        
        private void OnViasNombreViaLocalidadOperationCompleted(object arg) {
            if ((this.ViasNombreViaLocalidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViasNombreViaLocalidadCompleted(this, new ViasNombreViaLocalidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public enum Idioma {
        
        /// <remarks/>
        Castellano,
        
        /// <remarks/>
        Euskera,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public partial class GDPClass {
        
        private Municipio[] municipioField;
        
        private EntidadSingular[] entidadSingularField;
        
        private Via[] viaField;
        
        private NumPostal[] numPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Municipio")]
        public Municipio[] Municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntidadSingular")]
        public EntidadSingular[] EntidadSingular {
            get {
                return this.entidadSingularField;
            }
            set {
                this.entidadSingularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Via")]
        public Via[] Via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NumPostal")]
        public NumPostal[] NumPostal {
            get {
                return this.numPostalField;
            }
            set {
                this.numPostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public partial class Municipio {
        
        private short codMunField;
        
        private string denomMunField;
        
        /// <remarks/>
        public short CodMun {
            get {
                return this.codMunField;
            }
            set {
                this.codMunField = value;
            }
        }
        
        /// <remarks/>
        public string DenomMun {
            get {
                return this.denomMunField;
            }
            set {
                this.denomMunField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public partial class NumPostal {
        
        private int codViaField;
        
        private int codPortalField;
        
        private string numeroField;
        
        private string nomCasaField;
        
        private System.Nullable<int> codPostalField;
        
        private short poligonoField;
        
        private short parcelaField;
        
        private System.Nullable<decimal> xField;
        
        private System.Nullable<decimal> yField;
        
        /// <remarks/>
        public int CodVia {
            get {
                return this.codViaField;
            }
            set {
                this.codViaField = value;
            }
        }
        
        /// <remarks/>
        public int CodPortal {
            get {
                return this.codPortalField;
            }
            set {
                this.codPortalField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string NomCasa {
            get {
                return this.nomCasaField;
            }
            set {
                this.nomCasaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CodPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
            }
        }
        
        /// <remarks/>
        public short Poligono {
            get {
                return this.poligonoField;
            }
            set {
                this.poligonoField = value;
            }
        }
        
        /// <remarks/>
        public short Parcela {
            get {
                return this.parcelaField;
            }
            set {
                this.parcelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public partial class Via {
        
        private int codViaField;
        
        private short codEntSingField;
        
        private string denomViaField;
        
        private string tipoField;
        
        private int codINEField;
        
        private string denomViaAbreviadaField;
        
        private string denomViaSimpleField;
        
        /// <remarks/>
        public int CodVia {
            get {
                return this.codViaField;
            }
            set {
                this.codViaField = value;
            }
        }
        
        /// <remarks/>
        public short CodEntSing {
            get {
                return this.codEntSingField;
            }
            set {
                this.codEntSingField = value;
            }
        }
        
        /// <remarks/>
        public string DenomVia {
            get {
                return this.denomViaField;
            }
            set {
                this.denomViaField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int CodINE {
            get {
                return this.codINEField;
            }
            set {
                this.codINEField = value;
            }
        }
        
        /// <remarks/>
        public string DenomViaAbreviada {
            get {
                return this.denomViaAbreviadaField;
            }
            set {
                this.denomViaAbreviadaField = value;
            }
        }
        
        /// <remarks/>
        public string DenomViaSimple {
            get {
                return this.denomViaSimpleField;
            }
            set {
                this.denomViaSimpleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36392")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tracasa.es/Schemas/GDP/")]
    public partial class EntidadSingular {
        
        private short codEntSingField;
        
        private short codMunField;
        
        private short codEntINEField;
        
        private string denomEntSingField;
        
        /// <remarks/>
        public short CodEntSing {
            get {
                return this.codEntSingField;
            }
            set {
                this.codEntSingField = value;
            }
        }
        
        /// <remarks/>
        public short CodMun {
            get {
                return this.codMunField;
            }
            set {
                this.codMunField = value;
            }
        }
        
        /// <remarks/>
        public short CodEntINE {
            get {
                return this.codEntINEField;
            }
            set {
                this.codEntINEField = value;
            }
        }
        
        /// <remarks/>
        public string DenomEntSing {
            get {
                return this.denomEntSingField;
            }
            set {
                this.denomEntSingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void EntidadesSingularesCompletedEventHandler(object sender, EntidadesSingularesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntidadesSingularesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EntidadesSingularesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void EntidadesSingularesMuniCompletedEventHandler(object sender, EntidadesSingularesMuniCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntidadesSingularesMuniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EntidadesSingularesMuniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void MunicipiosCompletedEventHandler(object sender, MunicipiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MunicipiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MunicipiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalCompletedEventHandler(object sender, PostalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalCodPortalCompletedEventHandler(object sender, PostalCodPortalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalCodPortalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalCodPortalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalesCompletedEventHandler(object sender, PostalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalesEntidadNombreCasaCompletedEventHandler(object sender, PostalesEntidadNombreCasaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalesEntidadNombreCasaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalesEntidadNombreCasaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalesNombreEntidadSingularCompletedEventHandler(object sender, PostalesNombreEntidadSingularCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalesNombreEntidadSingularCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalesNombreEntidadSingularCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalesNombreLocalidadCompletedEventHandler(object sender, PostalesNombreLocalidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalesNombreLocalidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalesNombreLocalidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void PostalesViaNombreCasaCompletedEventHandler(object sender, PostalesViaNombreCasaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostalesViaNombreCasaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostalesViaNombreCasaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ViaCompletedEventHandler(object sender, ViaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ViasEntidadSingularCompletedEventHandler(object sender, ViasEntidadSingularCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViasEntidadSingularCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViasEntidadSingularCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ViasLocalidadCompletedEventHandler(object sender, ViasLocalidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViasLocalidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViasLocalidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ViasMunicipiosCompletedEventHandler(object sender, ViasMunicipiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViasMunicipiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViasMunicipiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ViasNombreViaEntSingularCompletedEventHandler(object sender, ViasNombreViaEntSingularCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViasNombreViaEntSingularCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViasNombreViaEntSingularCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ViasNombreViaLocalidadCompletedEventHandler(object sender, ViasNombreViaLocalidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViasNombreViaLocalidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViasNombreViaLocalidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GDPClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GDPClass)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591